name: Continuous Integration

on :
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install packages
        run: npm ci

      - name: Linter
        run: npm run lint

    #   - name: Run tests
    #     run: npm test

      - name: Build
        run: npm run build

